package pers.ljy.background.model;


import java.io.Serializable;
import java.util.Date;

/***
 * 日志纪录
 * @author ljy
 *
 */
public class SysLogsEntity implements Serializable {
    /**
     * id
     */
    private Long id;

    /**
     * 用户ID
     */
    private Integer userId;

    /**
     * 日志类型：1001：正常  1002：异常
     */
    private String logsType;

    /**
     * 请求url
     */
    private String url;

    /**
     * 请求IP
     */
    private String ip;

    /**
     * 请求类路径
     */
    private String classPath;

    /**
     * 请求方法
     */
    private String askMethod;

    /**
     * 请求方法全路径
     */
    private String methodPath;

    /**
     * 请求方式
     */
    private String requestMethod;

    /**
     * 描述
     */
    private String description;

    /**
     * 异常代码
     */
    private String errorCode;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * 请求参数
     */
    private String params;

    /**
     * 异常信息
     */
    private String errorMsg;

    /**
     * 请求方法返回值
     */
    private String methodResultValue;
    
    /**
     * 方法执行消耗时间转换值
     */
    private String wasteTimeMsg;
    
    /**
     * 方法消耗时间(秒为单位)
     */
    private Long wasteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_logs
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     * @return id_
     */
    public Long getId() {
        return id;
    }

    /**
     * id
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户ID
     * @return user_id_
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 用户ID
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 日志类型：1001：正常  1002：异常
     * @return logs_type_
     */
    public String getLogsType() {
        return logsType;
    }

    /**
     * 日志类型：1001：正常  1002：异常
     * @param logsType
     */
    public void setLogsType(String logsType) {
        this.logsType = logsType == null ? null : logsType.trim();
    }

    /**
     * 请求url
     * @return url_
     */
    public String getUrl() {
        return url;
    }

    /**
     * 请求url
     * @param url
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * 请求IP
     * @return ip_
     */
    public String getIp() {
        return ip;
    }

    /**
     * 请求IP
     * @param ip
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * 请求类路径
     * @return class_path_
     */
    public String getClassPath() {
        return classPath;
    }

    /**
     * 请求类路径
     * @param classPath
     */
    public void setClassPath(String classPath) {
        this.classPath = classPath == null ? null : classPath.trim();
    }

    /**
     * 请求方法
     * @return ask_method_
     */
    public String getAskMethod() {
        return askMethod;
    }

    /**
     * 请求方法
     * @param askMethod
     */
    public void setAskMethod(String askMethod) {
        this.askMethod = askMethod == null ? null : askMethod.trim();
    }

    /**
     * 请求方法全路径
     * @return method_path_
     */
    public String getMethodPath() {
        return methodPath;
    }

    /**
     * 请求方法全路径
     * @param methodPath
     */
    public void setMethodPath(String methodPath) {
        this.methodPath = methodPath == null ? null : methodPath.trim();
    }

    /**
     * 请求方式
     * @return request_method_
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * 请求方式
     * @param requestMethod
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }

    /**
     * 描述
     * @return description_
     */
    public String getDescription() {
        return description;
    }

    /**
     * 描述
     * @param description
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 异常代码
     * @return error_code_
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * 异常代码
     * @param errorCode
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * 创建时间
     * @return create_date_
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * 创建时间
     * @param createDate
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * 请求参数
     * @return params_
     */
    public String getParams() {
        return params;
    }

    /**
     * 请求参数
     * @param params
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * 异常信息
     * @return error_msg_
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * 异常信息
     * @param errorMsg
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * 请求方法返回值
     * @return method_result_value_
     */
    public String getMethodResultValue() {
        return methodResultValue;
    }

    /**
     * 请求方法返回值
     * @param methodResultValue
     */
    public void setMethodResultValue(String methodResultValue) {
        this.methodResultValue = methodResultValue == null ? null : methodResultValue.trim();
    }

	public String getWasteTimeMsg() {
		return wasteTimeMsg;
	}

	public void setWasteTimeMsg(String wasteTimeMsg) {
		this.wasteTimeMsg = wasteTimeMsg;
	}

	public Long getWasteTime() {
		return wasteTime;
	}

	public void setWasteTime(Long wasteTime) {
		this.wasteTime = wasteTime;
	}
    
    
}