package pers.ljy.background.model;


import java.io.Serializable;
import java.util.Date;

/***
 * 资源菜单
 * @author ljy
 *
 */
public class SysResourceMenusEntity implements Serializable {
    /**
     * id
     */
    private Integer id;

    /**
     * 菜单编号
     */
    private String menuNumber;

    /**
     * 菜单名称
     */
    private String menuName;

    /**
     * 菜单类型(1001：目录  1002:菜单  1003：按钮)
     */
    private String menuType;

    /**
     * 父级
     */
    private String parentMenuNumber;

    /**
     * 序号
     */
    private Byte serialNumber;

    /**
     * 图标
     */
    private String menuIcon;

    /**
     * URL
     */
    private String menuUrl;

    /**
     * 授权标识(多个用逗号分隔，如：user:list,user:create)
     */
    private String authorizedSigns;

    /**
     * 状态 1001：禁用   1002：正常
     */
    private String status;

    /**
     * 创建人
     */
    private Date createDate;

    /**
     * 创建时间
     */
    private Integer createUserId;

    /**
     * 修改人
     */
    private Integer updateUserId;

    /**
     * 修改时间
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resource_menus
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     * @return id_
     */
    public Integer getId() {
        return id;
    }

    /**
     * id
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 菜单编号
     * @return menu_number_
     */
    public String getMenuNumber() {
        return menuNumber;
    }

    /**
     * 菜单编号
     * @param menuNumber
     */
    public void setMenuNumber(String menuNumber) {
        this.menuNumber = menuNumber == null ? null : menuNumber.trim();
    }

    /**
     * 菜单名称
     * @return menu_name_
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * 菜单名称
     * @param menuName
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * 菜单类型(1001：目录  1002:菜单  1003：按钮)
     * @return menu_type_
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * 菜单类型(1001：目录  1002:菜单  1003：按钮)
     * @param menuType
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * 父级
     * @return parent_menu_number_
     */
    public String getParentMenuNumber() {
        return parentMenuNumber;
    }

    /**
     * 父级
     * @param parentMenuNumber
     */
    public void setParentMenuNumber(String parentMenuNumber) {
        this.parentMenuNumber = parentMenuNumber == null ? null : parentMenuNumber.trim();
    }

    /**
     * 序号
     * @return serial_number_
     */
    public Byte getSerialNumber() {
        return serialNumber;
    }

    /**
     * 序号
     * @param serialNumber
     */
    public void setSerialNumber(Byte serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * 图标
     * @return menu_icon_
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * 图标
     * @param menuIcon
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon == null ? null : menuIcon.trim();
    }

    /**
     * URL
     * @return menu_url_
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * URL
     * @param menuUrl
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * 授权标识(多个用逗号分隔，如：user:list,user:create)
     * @return authorized_signs_
     */
    public String getAuthorizedSigns() {
        return authorizedSigns;
    }

    /**
     * 授权标识(多个用逗号分隔，如：user:list,user:create)
     * @param authorizedSigns
     */
    public void setAuthorizedSigns(String authorizedSigns) {
        this.authorizedSigns = authorizedSigns == null ? null : authorizedSigns.trim();
    }

    /**
     * 状态 1001：禁用   1002：正常
     * @return status_
     */
    public String getStatus() {
        return status;
    }

    /**
     * 状态 1001：禁用   1002：正常
     * @param status
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 创建人
     * @return create_date_
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * 创建人
     * @param createDate
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * 创建时间
     * @return create_user_id_
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * 创建时间
     * @param createUserId
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * 修改人
     * @return update_user_id_
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * 修改人
     * @param updateUserId
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * 修改时间
     * @return update_date_
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * 修改时间
     * @param updateDate
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}