package pers.ljy.background.model;


import java.io.Serializable;
import java.util.Date;

/***
 * 角色
 * @author ljy
 *
 */
public class SysRoleEntity implements Serializable {
    /**
     * id
     */
    private Integer id;

    /**
     * 角色名称
     */
    private String roleName;

    /**
     * 备注
     */
    private String remarks;

    /**
     * 状态 1001：禁用   1002：正常
     */
    private String status;

    /**
     * 创建人
     */
    private Date createDate;

    /**
     * 创建时间
     */
    private Integer createUserId;

    /**
     * 修改人
     */
    private Integer updateUserId;

    /**
     * 修改时间
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     * @return id_
     */
    public Integer getId() {
        return id;
    }

    /**
     * id
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 角色名称
     * @return role_name_
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * 角色名称
     * @param roleName
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * 备注
     * @return remarks_
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * 备注
     * @param remarks
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * 状态 1001：禁用   1002：正常
     * @return status_
     */
    public String getStatus() {
        return status;
    }

    /**
     * 状态 1001：禁用   1002：正常
     * @param status
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 创建人
     * @return create_date_
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * 创建人
     * @param createDate
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * 创建时间
     * @return create_user_id_
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * 创建时间
     * @param createUserId
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * 修改人
     * @return update_user_id_
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * 修改人
     * @param updateUserId
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * 修改时间
     * @return update_date_
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * 修改时间
     * @param updateDate
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}