package pers.ljy.background.model;


import java.io.Serializable;
import java.util.Date;

/***
 * 账户
 * @author ljy
 *
 */
public class SysUsersAccountEntity implements Serializable {
    /**
     * id
     */
    private Integer id;

    /**
     * 用户编号
     */
    private String userNumber;

    /**
     * 用户ID
     */
    private Integer userId;

    /**
     * 用户名
     */
    private String userName;

    /**
     * 用户密码
     */
    private String userPwd;

    /**
     * 帐号类型  1001：普通用户 
     */
    private String accountType;

    /**
     * 积分
     */
    private Long integral;

    /**
     * 状态 1001：禁用   1002：正常
     */
    private String status;

    /**
     * 盐值
     */
    private String salt;

    /**
     * 注册时间
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_users_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     * @return id_
     */
    public Integer getId() {
        return id;
    }

    /**
     * id
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 用户编号
     * @return user_number_
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * 用户编号
     * @param userNumber
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    /**
     * 用户ID
     * @return user_id_
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 用户ID
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 用户名
     * @return user_name_
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 用户名
     * @param userName
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 用户密码
     * @return user_pwd_
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * 用户密码
     * @param userPwd
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * 帐号类型  1001：普通用户 
     * @return account_type_
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * 帐号类型  1001：普通用户 
     * @param accountType
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * 积分
     * @return integral_
     */
    public Long getIntegral() {
        return integral;
    }

    /**
     * 积分
     * @param integral
     */
    public void setIntegral(Long integral) {
        this.integral = integral;
    }

    /**
     * 状态 1001：禁用   1002：正常
     * @return status_
     */
    public String getStatus() {
        return status;
    }

    /**
     * 状态 1001：禁用   1002：正常
     * @param status
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 盐值
     * @return salt_
     */
    public String getSalt() {
        return salt;
    }

    /**
     * 盐值
     * @param salt
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * 注册时间
     * @return create_date_
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * 注册时间
     * @param createDate
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}